### ISSUE TITLE
Direct match attributes in lib funs to icinga2 objects attributes

### ISSUE THREAD

**Issue by scopenco** [bodsch/ruby-icinga2#21]
Hello,

I found that this lib doesn't have a direct match to icinga2 object attributes.

for example section in `lib/icinga2/hosts.rb`
```
      payload = {
        'templates' => [ 'generic-host' ],
        'attrs'     => {
          'address'              => fqdn,
          'display_name'         => display_name,
          'max_check_attempts'   => max_check_attempts.to_i,
          'check_interval'       => check_interval.to_i,
          'retry_interval'       => retry_interval.to_i,
          'enable_notifications' => notifications,
          'action_url'           => action_url,
          'notes'                => notes,
          'notes_url'            => notes_url
        }
      }
```

so I have to look at this library file and find that to set `address` attribute I have to define `fqdn` in `add_host` options. This is strange because i'm waiting that setting 'address' in options will set the same attribute in object. Agree?

What do you think if I'll send PR that will do direct match from funcs options to icinga2 object options?

**Comment by bodsch** [comment]
You are welcome! :)
I have not yet been able to implement all API calls.
but I'm happy about every pull request! :)

**Comment by scopenco** [comment]
PR already pushed https://github.com/bodsch/ruby-icinga2/pull/22

**Comment by bodsch** [comment]
Thank you!
i will fix the merge conflicts ASAP to integrate your PR

**Comment by scopenco** [comment]
This PR https://github.com/bodsch/ruby-icinga2/pull/24 don't have conflicts. It's the same code but rebased to `stable/1.0.0-beta1`

**Comment by bodsch** [comment]
i see.
TravisCI had a mistake with the spec tests.
i fixed it und merged your PR.

Thanks for that!

**Comment by scopenco** [comment]
When do you plan to release new version to rubygems? I want to send you one more PR for `service` object.

**Comment by bodsch** [comment]
i've planned the 1.0 release to the OSMC ar nuremberg this week.
but it not possible, i'm a speaker and i a little bit nervous. :)
i think, next week is a better time for talk about it.
